config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'payments/new'

  get 'orders/new'

  get 'orders/create'

  get 'orders/confirm'

  get 'orders/result'

  get 'orders/fail'

  get 'games/play'

  root 'posts#index'
  resources :payments
  resources :orders do
    member do
      get :confirm
    end
    collection do
      get :fail
      post :result
    end
  end
  resources :posts do
    collection do
      get :questions
      get :top
      get :switch_case
    end
  end
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  namespace :admin do
    root 'users#index'
    resources :users do
      member do
        post :change_status
        post :change_admin
        post :change_balance
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @post = Post.new
  end

  def questions
    
  end

  def switch_case
    if user_signed_in?
      current_user.switch_case(params[:case_type])
      render 'posts/switch_case'
      #redirect_back(fallback_location: root_path)
    else
      redirect_to user_vkontakte_omniauth_authorize_path
    end
  end

  def create
    @post = Post.new(post_params)
  end

  def top
    @top_users = User.order(credit_history: :desc).limit(7)
    @avatars = []
    @top_users.each_with_index do |user, index|
      first_uri = URI.parse "https://api.vk.com/method/users.get?user_id=#{user.uid}&fields=photo_100&v=5.52&access_token=61183cdd61183cdd61183cddfb6145300a6611861183cdd3841350b99693d0b1a2c277d"
      first_result = Net::HTTP.get(first_uri)
      first_parsed_result = JSON.parse(first_result)
      first_avatar = first_parsed_result['response'][0]['photo_100']
      @avatars << first_avatar
    end
    @avatars
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_carousel.html.erb
<div class="case-open">
  <div class="case-open__ico case-open__ico--1"><img src="/img/case-img.png" alt="case"></div>
  <div class="case-open__ico case-open__ico--2"><img src="/img/case-ico3.png" alt="case"></div>
  <img src="/img/case-open.png" class="case1"  alt="case">
  <img src="/img/bg-case.jpg" class="case2" alt="case">
  <div class="carousel" id="carousel_out">
    <div class="slider_item owl-carousel owl-theme" id="carousel_in">
      <% unless user_signed_in?  %>
        <%= render 'carousel1' %>
        <%= render 'carousel2' %>
      <% else %>
        <% if current_user.case_type == 1 %>
          <%= render 'carousel1' %>
        <% elsif current_user.case_type == 2 %>
          <%= render 'carousel2' %>
        <% end  %>
      <% end %>
    </div>
  </div>
  <img src="/img/1204-naklejka-Pricel.png" alt="pricel" class="pricel">
</div>

app/views/posts/_carousel1.html.erb
<div class="item_car" data-hash="1">
  <img src="/img/case1/case1-Glock-18C.png" alt="">
  <div class="weapon-item__info">
    <p>Саперная Лопатка</p>
    <b>30 К</b>
  </div>
</div>
<div class="item_car" data-hash="2">
  <img src="/img/case1/case1-SIG-Sauer-P226-C.png" alt="">
  <div class="weapon-item__info">
    <p>SIG Sauer P226 C</p>
    <b>60 К</b>
  </div>
</div>
<div class="item_car" data-hash="3">
  <img src="/img/case1/case1-VSS-Vintorez.png" alt="">
  <div class="weapon-item__info">
    <p>ВСС Винторез</p>
    <b>90 К</b>
  </div>
</div>
<div class="item_car" data-hash="4">
  <img src="/img/case1/case1-FN-F2000.png" alt="">
  <div class="weapon-item__info">
    <p>MSBS Radon</p>
    <b>160 К</b>
  </div>
</div>
<div class="item_car" data-hash="5">
  <img src="/img/case1/case1-Honey-Badger.png" alt="">
  <div class="weapon-item__info">
    <p>Kel-Tec Shotgun</p>
    <b>200 К</b>
  </div>
</div>
<div class="item_car" data-hash="6">
  <img src="/img/case1/case1-Steyr-Scout.png" alt="">
  <div class="weapon-item__info">
    <p>AX308</p>
    <b>300 К</b>
  </div>
</div>
<div class="item_car" data-hash="7">
  <img src="/img/case1/case1-M16A3.png" alt="">
  <div class="weapon-item__info">
    <p>M16A3</p>
    <b>500 К</b>
  </div>
</div>
<div class="item_car" data-hash="8">
  <img src="/img/case1/case1-AS50.png" alt="">
  <div class="weapon-item__info">
    <p>AS50</p>
    <b>750 К</b>
  </div>
</div>
<div class="item_car" data-hash="9">
  <img src="/img/case1/case1-Gold-M14 Crazy Horse.png" alt="">
  <div class="weapon-item__info">
    <p>Золотая M14 Crazy Horse</p>
    <b>1000 К</b>
  </div>
</div>
<div class="item_car" data-hash="10">
  <img src="/img/case1/case1-Gold-Magpul FMG-9.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой Magpul FMG-9</p>
    <b>2000 К</b>
  </div>
</div>
<div class="item_car" data-hash="11">
  <img src="/img/case1/case1-Gold-SVU-AS.png" alt="">
  <div class="weapon-item__info">
    <p>Золотая СВУ-АС</p>
    <b>3500 К</b>
  </div>
</div>
<div class="item_car" data-hash="12">
  <img src="/img/case1/case1-Gold-Enfield L85A2.png" alt="">
  <div class="weapon-item__info">
    <p>Золотая Enfield L85A2</p>
    <b>5000 К</b>
  </div>
</div>
<div class="item_car" data-hash="13">
  <img src="/img/case1/case1-Gold-Fabarm STF 12.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой Fabarm STF 12</p>
    <b>7500 К</b>
  </div>
</div>
<div class="item_car" data-hash="14">
  <img src="/img/case1/case1-Gold-SCAR-L PDW.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой SCAR-L PDW</p>
    <b>10000 К</b>
  </div>
</div>
<div class="item_car" data-hash="15">
  <img src="/img/case1/case1-Gold-M16A3.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой M16A3</p>
    <b>15000 К</b>
  </div>
</div>
<div class="item_car" data-hash="16">
  <img src="/img/case1/case1-Gold-Saiga-12C.png" alt="">
  <div class="weapon-item__info">
    <p>Золотая Сайга-12С</p>
    <b>25000 К</b>
  </div>
</div>

app/views/posts/_carousel2.html.erb
<div class="item_car" data-hash="17">
  <img src="/img/case2/AA-12.png" alt="">
  <div class="weapon-item__info">
    <p>Турнирные шлема</p>
    <b>40 К</b>
  </div>
</div>
<div class="item_car" data-hash="18">
  <img src="/img/case2/AK-47.png" alt="">
  <div class="weapon-item__info">
    <p>AUG A3 9mm</p>
    <b>80 К</b>
  </div>
</div>
<div class="item_car" data-hash="19">
  <img src="/img/case2/AT308.png" alt="">
  <div class="weapon-item__info">
    <p>AT308</p>
    <b>160 К</b>
  </div>
</div>
<div class="item_car" data-hash="20">
  <img src="/img/case2/XM8-Compact.png" alt="">
  <div class="weapon-item__info">
    <p>M14 Crazy Horse</p>
    <b>320 К</b>
  </div>
</div>
<div class="item_car" data-hash="21">
  <img src="/img/case2/Tavor-CTAR-21.png" alt="">
  <div class="weapon-item__info">
    <p>McMillan CS5</p>
    <b>400 К</b>
  </div>
</div>
<div class="item_car" data-hash="22">
  <img src="/img/case2/Calico-M951S.png" alt="">
  <div class="weapon-item__info">
    <p>Calico M951S</p>
    <b>500 К</b>
  </div>
</div>
<div class="item_car" data-hash="23">
  <img src="/img/case2/USAS-12.png" alt="">
  <div class="weapon-item__info">
    <p>USAS 12</p>
    <b>750 К</b>
  </div>
</div>
<div class="item_car" data-hash="24">
  <img src="/img/case2/Gold-DP-12.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой DP 12</p>
    <b>1000 К</b>
  </div>
</div>
<div class="item_car" data-hash="25">
  <img src="/img/case2/Gold-M249-Para.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой M249 Para</p>
    <b>1500 К</b>
  </div>
</div>
<div class="item_car" data-hash="26">
  <img src="/img/case2/Gold-MAG-7.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой MAG 7</p>
    <b>2500 К</b>
  </div>
</div>
<div class="item_car" data-hash="27">
  <img src="/img/case2/Gold-Steyr-Scout.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой Steyr Scout</p>
    <b>5000 К</b>
  </div>
</div>
<div class="item_car" data-hash="28">
  <img src="/img/case2/Gold-AX308.png" alt="">
  <div class="weapon-item__info">
    <p>Золотая AX308</p>
    <b>7500 К</b>
  </div>
</div>
<div class="item_car" data-hash="29">
  <img src="/img/case2/Gold-Honey-Badger.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой Honey Badger</p>
    <b>10000 К</b>
  </div>
</div>
<div class="item_car" data-hash="30">
  <img src="/img/case2/Gold-FN-SCAR-H.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой FN SCAR-H</p>
    <b>15000 К</b>
  </div>
</div>
<div class="item_car" data-hash="31">
  <img src="/img/case2/Gold-AS50.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой AS50</p>
    <b>25000 К</b>
  </div>
</div>
<div class="item_car" data-hash="32">
  <img src="/img/case2/Gold-Tavor-CTAR-21.png" alt="">
  <div class="weapon-item__info">
    <p>Золотой Tavor CTAR-21</p>
    <b>35000 К</b>
  </div>
</div>

app/views/posts/_case1.html.erb
<div class="tabs__content tabs__content_active" id="content1">
  <div class="weapon-wrap">
    <div class="line line--vertical line--1"></div>
    <div class="line line--vertical line--2"></div>
    <div class="line line--vertical line--3"></div>
    <div class="line line--vertical line--4"></div>
    <div class="line line--vertical line--5"></div>
    <div class="line line--horizontal line--6"></div>
    <div class="line line--horizontal line--7"></div>
    <div class="line line--horizontal line--8"></div>
    <div class="line line--horizontal line--9"></div>
    <div class="line line--horizontal line--10"></div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Glock-18C.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Саперная Лопатка</p>
        <b>30 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-SIG-Sauer-P226-C.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>SIG Sauer P226 C</p>
        <b>60 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-VSS-Vintorez.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>ВСС Винторез</p>
        <b>90 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-FN-F2000.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>MSBS Radon</p>
        <b>160 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Honey-Badger.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Kel-Tec Shotgun</p>
        <b>200 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Steyr-Scout.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>AX308</p>
        <b>300 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-M16A3.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>M16A3</p>
        <b>500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-AS50.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>AS50</p>
        <b>750 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-M14 Crazy Horse.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотая M14 Crazy Horse</p>
        <b>1000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-Magpul FMG-9.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой Magpul FMG-9</p>
        <b>2000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-SVU-AS.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотая СВУ-АС</p>
        <b>3500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-Enfield L85A2.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотая Enfield L85A2</p>
        <b>5000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-Fabarm STF 12.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой Fabarm STF 12</p>
        <b>7500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-SCAR-L PDW.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой SCAR-L PDW</p>
        <b>10000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-M16A3.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой M16A3</p>
        <b>15000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case1/case1-Gold-Saiga-12C.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотая Сайга-12С</p>
        <b>25000 K</b>
      </div>
    </div>
  </div>
</div>

app/views/posts/_case2.html.erb
<div class="block__content in-case">
  <div class="weapon-wrap">

    <div class="line line--vertical line--1"></div>
    <div class="line line--vertical line--2"></div>
    <div class="line line--vertical line--3"></div>
    <div class="line line--vertical line--4"></div>
    <div class="line line--vertical line--5"></div>
    <div class="line line--horizontal line--6"></div>
    <div class="line line--horizontal line--7"></div>
    <div class="line line--horizontal line--8"></div>
    <div class="line line--horizontal line--9"></div>
    <div class="line line--horizontal line--10"></div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/AA-12.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Турнирные шлема</p>
        <b>40 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/AK-47.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>AUG A3 9mm</p>
        <b>80 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/AT308.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>AT308</p>
        <b>160 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/XM8-Compact.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>M14 Crazy Horse</p>
        <b>320 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Tavor-CTAR-21.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>McMillan CS5</p>
        <b>400 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Calico-M951S.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Calico M951S</p>
        <b>500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/USAS-12.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>USAS-12</p>
        <b>750 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-DP-12.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой DP-12</p>
        <b>1000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-M249-Para.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой M249 Para</p>
        <b>1500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-MAG-7.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой MAG-7</p>
        <b>2500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-Steyr-Scout.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой Steyr Scout</p>
        <b>5000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-AX308.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотая AX308</p>
        <b>7500 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-Honey-Badger.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой Remington R11</p>
        <b>10000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-FN-SCAR-H.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой FN SCAR-H</p>
        <b>15000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-AS50.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой AS50</p>
        <b>25000 К</b>
      </div>
    </div>
    <div class="weapon-item">
      <div class="weapon-item__img"><img src="/img/case2/Gold-Tavor-CTAR-21.png" alt="weapon"></div>
      <div class="weapon-item__info">
        <p>Золотой Tavor CTAR-21</p>
        <b>35000 К</b>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @style = 'style=' + 'background:#666666;' %>
<% if user_signed_in? %>
  <% current_user.case_type == 1 ? @case_type = 'РЕДКИЙ' : @case_type = 'ЛЕГЕНДАРНЫЙ' %>
<% end %>
<body>
<main>
  <section class="go-case" id="go-case-js">
    <div class="container">
      <h2 class="page-title">2 <span>Cases</span><i>выберете кейс</i></h2>
      <div id="js">
        <div class="case-wrap">
          <% if user_signed_in? %>
            <%= link_to switch_case_posts_path(case_type: 1), style: 'color: white;', remote: true do %>
                  <div class="case-item" <%= @style if current_user.case_type == 1 %>>
                <div class="case-item__ico"><img src="/img/case-ico1.png" alt="ico1"></div>
                <p>«Редкий»</p>
                <b><span>79</span> рублей</b>
              </div>
            <% end %>
            <%= link_to switch_case_posts_path(case_type: 2), style: 'color: white;', remote: true do %>
              <div class="case-item" <%= @style if current_user.case_type == 2 %>>
                <div class="case-item__ico"><img src="/img/case-ico2.png" alt="ico1"></div>
                <p>«Легендарный»</p>
                <b><span>159</span> рублей</b>
              </div>
            <% end %>
          <% else %>
              <%= link_to user_vkontakte_omniauth_authorize_path, style: 'color: white;' do %>
                  <div class="case-item">
                    <div class="case-item__ico"><img src="/img/case-ico1.png" alt="ico1"></div>
                    <p>«Редкий»</p>
                    <b><span>79</span> рублей</b>
                  </div>
              <% end %>
              <%= link_to user_vkontakte_omniauth_authorize_path, style: 'color: white;' do %>
                  <div class="case-item">
                    <div class="case-item__ico"><img src="/img/case-ico2.png" alt="ico1"></div>
                    <p>«Легендарный»</p>
                    <b><span>159</span> рублей</b>
                  </div>
              <% end %>
          <% end %>
        </div>
        <div id="test">
        <%= render 'carousel' %>
          <% unless user_signed_in? %>
              <div class="autorization">
                <button class="autorization__btn" onclick="location.href='/users/auth/vkontakte'"><img src="img/vk-btn.png" alt="vk"><span>вход через vk</span></button>
              </div>
          <% else %>
              <% if current_user.balance >= 79 %>
                  <a class="play-btn" id="play-btn" href="<%= games_play_path %>" data-remote="true">играть сейчас</a>
              <% else %>
                  <a class="play-btn btn_pop">Пополнить баланс</a>
              <% end %>
          <% end %>
        </div>
        <div class="block block--weapon">
          <div class="block__title">
            <h3><b>In your  <span>case</span></b><i> может выпасть</i></h3>
          </div>
          <div class="block__content in-case">
            <% if user_signed_in? %>
                <% if current_user.case_type == 1 %>
                  <%= render 'case1' %>
                <% elsif current_user.case_type == 2 %>
                  <%= render 'case2' %>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
  <div id="doors_js">
    <div class="doors">
      <div class="doors_left"></div>
      <div class="doors_right"></div>
      <!-- Я изменил этот блок, чтобы не путаться в стилях написал все здесь -->

      <!-- Старт -->
      <div class="bg_item_block">
        <div class="case_shield"><img style="position: absolute;left: 50%;top: 50%;-webkit-transform: translate(-50%, -50%);-ms-transform: translate(-50%, -50%);-o-transform: translate(-50%, -50%);transform: translate(-50%, -50%);" src="img/icon-case.png" alt=""></div>
        <h3 id="case_name" style="text-align: center; background-color: rgb(46, 48, 50); padding: 25px 0;">IN «<%= @case_type %>»:</h3>
        <div class="weapon-item">
          <div class="weapon-item__img">
            <img src="/img/case2/AA-12.png" alt="weapon">
          </div>
          <div class="weapon-item__info">
            <p> AA-12.png</p>
            <b>40 К</b>
          </div>
        </div>
      </div>
      <!-- КОНЕЦ -->
    </div>
  </div>
</main>
</body>

app/views/posts/new.html.erb
<main>
  <section class="teh-page">
    <div class="container">
      <h2 class="page-title">Техническая <span>Поддержка</span><i>Напишите нам</i></h2>
      <div class="teh-form">
        <form>
          <div class="input-wrap"><input type="text" placeholder="Имя"><i class="fa fa-user" aria-hidden="true"></i></div>
          <div class="input-wrap"><input type="password" placeholder="Введите адрес вк"><i class="fa fa-unlock-alt" aria-hidden="true"></i></div>
          <textarea></textarea>
          <div class="send-btn">
            <button>Отправить на email <span><i class="fa fa-share" aria-hidden="true"></i></span></button>
            <span>или</span>
            <a href="https://vk.com/im?media=&sel=-151179280"><img src="/img/vk-btn.png" alt="vk"></a>
          </div>
        </form>
      </div>
      <div class="contacts-bot">
        <div class="contacts-item">
          <b>Skype:</b>
          <a href="skype:torrentbig?call">torrentbig</a>
        </div>
        <div class="contacts-item">
          <b>почта:</b>
          <a href="mailto:warface_game_online@gmail.com">warface_game_online@gmail.com</a>
        </div>
        <div class="contacts-item">
          <b>Группа в вк:</b>
          <a href="https://vk.com/case_wf_drop">https://vk.com/case_wf_drop</a>
        </div>
      </div>
    </div>
  </section>
</main>